### ISSUE TITLE
your english filter is broken

### ISSUE THREAD

**Issue by exse2** [vuejs-community/vue-filter-pluralize#181]
its not just 2 combinations, it has "1st", "2nd", "3rd", "4th"... st, nd, rd, th are at least 4.

**Comment by exse2** [comment]
Maybe that helps:

export default function (i) {
	var j = i % 10,
		k = i % 100;
	if (j == 1 && k != 11) {
		return "st";
	}
	if (j == 2 && k != 12) {
		return "nd";
	}
	if (j == 3 && k != 13) {
		return "rd";
	}
	return "th";
};

**Comment by eduardnikolenko** [comment]
Oh no, this filter is not for this case.
In your case, ordinal numbers are used, but this filter operates with declensions of objects, not the numbers themselves.

By example:
```html
<template>
  <div>{{ count }} {{ count | pluralize('en', [/* one */ 'phone', /* many */ 'phones']) }}</div>
</template>

<script>
  export default {
    data() {
      return {
        count: 2
      }
    }
  };
</script>
```
render as:
```html
2 phones
```

**Comment by exse2** [comment]
Thank you! That wasn't clear in the README.md at all as I don't speak russian.
